# Generated by Django 4.1 on 2022-09-10 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.articulos')),
                ('publica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estudiantepublica')),
            ],
        ),
    ]
