# Generated by Django 4.1 on 2022-09-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_articulos_descripcion_publicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ManyToManyField(to='home.articulos')),
                ('comenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estudiantepublica')),
            ],
        ),
    ]
